### ISSUE TITLE
utils.py code file

### ISSUE THREAD

**Issue by Yeah123456ye** [Meiyan88/DMAAN#1]
Hello, sorry to bother you, can you please provide me the utils file? I am very interested in your paper and would like to reproduce the code, my e-mail is 2408747155@qq.com

**Comment by Meiyan88** [comment]
We have provided some functions in utils.py that can be modified according to your specific needs.

**Comment by Yeah123456ye** [comment]
> We have provided some functions in utils.py that can be modified according to your specific needs.
Thank you very much!

**Comment by Yeah123456ye** [comment]
Thank you very much!
